#!/usr/bin/env node
/* ============================================================
   build.mjs — bundle the game into one self-contained .html

   The dev build is ES modules across 21 files, which needs a
   web server: browsers refuse `type="module"` over file://.
   This produces a single document with the CSS and all the JS
   inlined as a classic script, so it runs by double-clicking it
   on a laptop, from an Android phone's Files app, or anywhere a
   static host can serve one page.

   Rather than concatenating modules (which would merge their
   scopes and let same-named module-level constants collide),
   each module is wrapped in a function and registered by path.
   `__req` runs it once, lazily, and caches its exports — the
   same semantics ES modules have, minus the loader.

   Usage:  node tools/build.mjs [--fragment]
     default     full standalone document -> dist/abyssal.html
     --fragment  body content only        -> dist/abyssal.fragment.html
   ============================================================ */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const ENTRY = 'main.js';

/* ---------------------------------------------------------- */
/* Module graph                                                */
/* ---------------------------------------------------------- */

const IMPORT_RE = /^import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"]\s*;?[ \t]*$/gm;
const EXPORT_DECL_RE = /^export\s+(class|const|let|var|function)\s+([A-Za-z_$][\w$]*)/gm;
const EXPORT_LIST_RE = /^export\s*\{([^}]*)\}\s*;?[ \t]*$/gm;

const modules = new Map();

/** Resolve an import specifier against the importing module's id. */
function resolve(fromId, spec) {
  if (!spec.startsWith('.')) throw new Error(`bare import not supported: ${spec}`);
  const id = posix.normalize(posix.join(posix.dirname(fromId), spec));
  if (id.startsWith('..')) throw new Error(`import escapes src/: ${spec} from ${fromId}`);
  return id;
}

/** Turn `a, b as c` into destructuring / assignment pairs. */
function parseSpecifiers(list) {
  return list
    .split(',')
    .map(s => s.trim())
    .filter(Boolean)
    .map(s => {
      const m = s.split(/\s+as\s+/);
      return m.length === 2 ? { local: m[0].trim(), exported: m[1].trim() }
                            : { local: s, exported: s };
    });
}

function load(id) {
  if (modules.has(id)) return;
  let code;
  try {
    code = readFileSync(join(SRC, id), 'utf8');
  } catch {
    throw new Error(`cannot read module ${id}`);
  }

  const deps = [];

  // import { a, b } from './x.js'  ->  const { a, b } = __req('x.js');
  code = code.replace(IMPORT_RE, (_, names, spec) => {
    const dep = resolve(id, spec);
    deps.push(dep);
    const bindings = parseSpecifiers(names)
      .map(({ local, exported }) => (local === exported ? local : `${local}: ${exported}`))
      .join(', ');
    return `const { ${bindings} } = __req(${JSON.stringify(dep)});`;
  });

  // Collect exported names, then strip the `export` keyword.
  const exported = new Set();
  for (const m of code.matchAll(EXPORT_DECL_RE)) exported.add(m[2]);
  code = code.replace(EXPORT_DECL_RE, '$1 $2');

  // export { A, B as C };  ->  removed, recorded as A->A, B->C
  const aliases = [];
  code = code.replace(EXPORT_LIST_RE, (_, list) => {
    for (const { local, exported: as } of parseSpecifiers(list)) aliases.push([as, local]);
    return '';
  });

  if (/^export\s/m.test(code)) {
    throw new Error(`${id}: unhandled export form remains after transform`);
  }

  const assignments = [
    ...[...exported].map(n => `  __x.${n} = ${n};`),
    ...aliases.map(([as, local]) => `  __x.${as} = ${local};`),
  ].join('\n');

  modules.set(id, { code, assignments, deps });
  for (const d of deps) load(d);
}

load(ENTRY);

/* ---------------------------------------------------------- */
/* Emit                                                        */
/* ---------------------------------------------------------- */

const indent = s => s.split('\n').map(l => (l ? '  ' + l : l)).join('\n');

const body = [...modules.entries()]
  .map(([id, m]) => `__def(${JSON.stringify(id)}, function (__x, __req) {\n${indent(m.code)}\n${m.assignments}\n});`)
  .join('\n\n');

const runtime = `/* ABYSSAL — Ocean Guardian.
   Bundled by tools/build.mjs from the ES-module sources in src/.
   Do not edit this file: edit src/ and rebuild with \`npm run build\`. */
(function () {
'use strict';

// Minimal module registry: run once, cache exports, same shape as ESM.
var __mods = Object.create(null);
function __def(id, fn) { __mods[id] = { fn: fn, exports: null }; }
function __req(id) {
  var m = __mods[id];
  if (!m) throw new Error('module not bundled: ' + id);
  if (!m.exports) { m.exports = {}; m.fn(m.exports, __req); }
  return m.exports;
}

${body}

__req(${JSON.stringify(ENTRY)});
})();`;

// A literal </script> anywhere in the source would close the tag early.
const safeJs = runtime.replace(/<\/script/gi, '<\\/script');
const css = readFileSync(join(SRC, 'styles.css'), 'utf8');

let html = readFileSync(join(ROOT, 'index.html'), 'utf8');
html = html.replace(
  /^\s*<link rel="stylesheet" href="src\/styles\.css" \/>\s*$/m,
  `<style>\n${css}\n</style>`
);
html = html.replace(
  /^\s*<script type="module" src="src\/main\.js"><\/script>\s*$/m,
  `<script>\n${safeJs}\n</script>`
);

if (html.includes('src/styles.css') || html.includes('src/main.js')) {
  throw new Error('inlining failed: index.html still references src/');
}

const fragment = process.argv.includes('--fragment');
mkdirSync(join(ROOT, 'dist'), { recursive: true });

let out, outPath;
if (fragment) {
  // Artifact hosting supplies its own <!doctype>/<head>/<body>; keep the
  // <title> so the page still names itself.
  const title = (html.match(/<title>([^<]*)<\/title>/) || [, 'ABYSSAL'])[1];
  const inner = html.slice(html.indexOf('<body>') + 6, html.lastIndexOf('</body>'));
  const style = html.slice(html.indexOf('<style>'), html.indexOf('</style>') + 8);
  out = `<title>${title}</title>\n${style}\n${inner.trim()}\n`;
  outPath = join(ROOT, 'dist', 'abyssal.fragment.html');
} else {
  out = html;
  outPath = join(ROOT, 'dist', 'abyssal.html');
}

writeFileSync(outPath, out);

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`${fragment ? 'fragment' : 'standalone'}: ${outPath.replace(ROOT + '/', '')}  ${kb} KB  (${modules.size} modules inlined)`);
